
** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused


** (process:2210): WARNING **: volume-control.vala:227: pa_context_connect() failed: Connection refused

